"""Count what is actually in the seed feeds, for the landing page to state.

The landing page makes quantitative claims about the dataset the product was
measured on. Those numbers used to be written by hand into the page, which is
the one thing this product argues nobody should do: a figure typed into a
paragraph is a figure nobody can check, and it goes stale the first time the
generator is re-run with different parameters.

So the page reads a file, and this writes it. Every number in the output is a
count of records in `seed/`, or a field copied from the evaluation answer keys
that ship beside them. Nothing here is estimated, rounded, or inferred.

`seed/` is git-ignored and regenerated by seedgen, so the JSON this emits is
committed instead: the landing page is a static route and there is no database
in a deploy container to ask at build time. Re-run this whenever the seed is
regenerated. If it is never re-run, the page keeps stating counts for a dataset
that no longer exists, which is why the output records the date it was made.

    python scripts/build_landing_aggregates.py
"""

from __future__ import annotations

import csv
import json
import sys
from collections import defaultdict
from datetime import date
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The landing page marks each planted defect at the row of the feed it was
# planted in, and a row is found by the same normalisation the matcher uses.
# Importing it rather than restating it is the point: a landing page that
# located its own marks with a private copy of the rule would be asserting a
# provenance it does not have.
sys.path.insert(0, str(ROOT / "packages" / "engine" / "src"))
from diligence_engine.normalise.invoice import norm_invoice_no  # noqa: E402

SEED = ROOT / "seed"
OUT = ROOT / "apps" / "web" / "app" / "product" / "aggregates.json"

# GSTR-2B nests documents under the supplier that filed them: `docdata.b2b` is
# a list of suppliers, each carrying an `inv` list. Counting the outer list
# counts suppliers and undercounts documents by roughly four to one, which is
# the sort of error that is invisible until someone checks it against the
# portal. These are the per-section keys the documents actually sit under.
DOCUMENT_KEYS = ("inv", "nt", "doclist", "boe")


def count_csv_rows(path: Path) -> int:
    """Data rows, excluding the header. Counted, not parsed."""
    if not path.exists():
        return 0
    with path.open(encoding="utf-8") as handle:
        return max(sum(1 for _ in handle) - 1, 0)


def count_gstr2b(path: Path) -> dict[str, int]:
    """Documents per section of one period's GSTR-2B."""
    payload = json.loads(path.read_text(encoding="utf-8"))
    docdata = payload["data"]["docdata"]
    counts: dict[str, int] = {}
    for section, suppliers in docdata.items():
        total = 0
        for supplier in suppliers:
            for key in DOCUMENT_KEYS:
                if key in supplier:
                    total += len(supplier[key])
        counts[section] = total
    return counts


_MONTHS = {
    m: f"{n:02d}"
    for n, m in enumerate(
        ("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"),
        start=1,
    )
}


def tally_period(raw: str) -> str | None:
    """The month of a Tally date, as YYYY-MM.

    Tally writes `16-Nov-2025`. Only the month is wanted, and an unrecognised
    date returns None rather than raising: a date this cannot read should cost
    one mark its position, not take the build down over a picture.
    """
    parts = raw.strip().split("-")
    if len(parts) != 3:
        return None
    month = _MONTHS.get(parts[1][:3].title())
    return f"{parts[2]}-{month}" if month else None


def defect_rows(slug: str, defects: list[dict]) -> dict[str, list[int]]:
    """Where in each feed the planted defects actually sit, as row indices.

    Purchase invoices are located by normalised document number, because a
    Tally voucher series is written by hand and the answer key holds the
    reduced form: "PUR/INV/2025-26/01691" and "1691" are the same document.
    Bank transactions are located by the reference the statement carries,
    which is machine-generated and needs no reduction.

    A normalised number that matches two rows is not a failure to resolve. It
    is the `duplicate_invoice` defect, whose whole nature is that the document
    was booked twice, and both rows are marked because both are the finding.
    """
    feeds = SEED / slug / "feeds"

    purchase = list(csv.DictReader((feeds / "tally_purchase_register.csv").open(encoding="utf-8")))
    by_number: dict[str, list[int]] = defaultdict(list)
    row_period: dict[int, str] = {}
    for i, row in enumerate(purchase):
        by_number[norm_invoice_no(row["Voucher No"])].append(i)
        period_of_row = tally_period(row["Date"])
        if period_of_row:
            row_period[i] = period_of_row

    bank = list(csv.DictReader((feeds / "bank_statement.csv").open(encoding="utf-8")))
    by_ref: dict[str, list[int]] = defaultdict(list)
    for i, row in enumerate(bank):
        ref = row["Chq / Ref No"].strip()
        if ref:
            by_ref[ref].append(i)

    found: dict[str, list[int]] = {"books": [], "bank": []}
    unresolved: list[str] = []
    for defect in defects:
        kind = defect["target_kind"]
        if kind == "purchase_invoice":
            hits = by_number.get(norm_invoice_no(defect["natural_key"]["number"]), [])
            # A normalised number can collide across two genuinely different
            # documents: in the seed, `BILL6239` and `TI/2026-27/6239` both
            # reduce to 6239 and sit a thousand rows apart. Marking both would
            # put a defect on a row that does not have one, on the page that
            # argues no figure should appear without its source. The month
            # separates them; a real duplicate shares it and stays marked
            # twice.
            period = defect["natural_key"].get("period") or defect.get("period")
            if len(hits) > 1 and period:
                in_period = [i for i in hits if row_period.get(i) == period]
                if in_period:
                    hits = in_period
            target = "books"
        elif kind == "bank_txn":
            hits = by_ref.get(defect["natural_key"]["ref_no"], [])
            target = "bank"
        else:
            # `company` targets a month's aggregate, not a row. Those are the
            # period-level rules, and they are counted separately rather than
            # given a position they do not have.
            continue
        if not hits:
            unresolved.append(f"{kind} {defect['natural_key']}")
            continue
        found[target].extend(hits)

    if unresolved:
        raise SystemExit(
            "planted defects that no feed row matches, so the seed and the "
            "answer key have diverged: " + "; ".join(unresolved)
        )

    return {k: sorted(set(v)) for k, v in found.items()}


def company(slug: str) -> dict:
    feeds = SEED / slug / "feeds"
    answers = SEED / slug / "answers"

    periods = sorted(p.stem.replace("gstr2b_", "") for p in feeds.glob("gstr2b_*.json"))
    sections: dict[str, int] = {}
    for period in periods:
        for section, n in count_gstr2b(feeds / f"gstr2b_{period}.json").items():
            sections[section] = sections.get(section, 0) + n

    key = json.loads((answers / "planted_defects.json").read_text(encoding="utf-8"))
    evaluation = json.loads((answers / "evaluation.json").read_text(encoding="utf-8"))

    # `false_positives` is a list of findings the engine raised that the answer
    # key does not contain. The page says the engine invented nothing, and this
    # is the number that claim is: its length, not a boolean someone set.
    false_positives = len(evaluation["row_level"]["false_positives"])

    rows = defect_rows(slug, key["defects"])

    return {
        "slug": slug,
        "name": key["company"],
        "defect_rows": rows,
        "_defects": key["defects"],
        "gstin": key["gstin"],
        "periods": len(periods),
        "period_from": periods[0].replace("_", "-"),
        "period_to": periods[-1].replace("_", "-"),
        "records": {
            "purchase_register": count_csv_rows(feeds / "tally_purchase_register.csv"),
            "sales_register": count_csv_rows(feeds / "tally_sales_register.csv"),
            "ledger_entries": count_csv_rows(feeds / "tally_ledger_entries.csv"),
            "gstr2b_documents": sum(sections.values()),
            "bank_statement": count_csv_rows(feeds / "bank_statement.csv"),
        },
        "gstr2b_sections": sections,
        "evaluation": {
            "planted": evaluation["planted"],
            "detected": evaluation["detected"],
            "missed": evaluation["missed"],
            "false_positives": false_positives,
            "row_level_planted": evaluation["row_level"]["planted"],
            "period_level_planted": evaluation["period_level"]["planted"],
        },
        "by_defect_type": {
            name: {"planted": d["planted"], "detected": d["detected"], "rule": d["rule"]}
            for name, d in evaluation["by_defect_type"].items()
        },
    }


def main() -> None:
    slugs = sorted(p.name for p in SEED.iterdir() if p.is_dir())
    if not slugs:
        raise SystemExit("seed/ is empty. It is git-ignored and regenerated: run seedgen first.")

    companies = [company(slug) for slug in slugs]

    # Every period in the seed is the same twelve months, so a differing count
    # means the seed was regenerated unevenly and the page would state a range
    # that only one company has. Better to stop than to publish the maximum.
    spans = {(c["periods"], c["period_from"], c["period_to"]) for c in companies}
    if len(spans) != 1:
        raise SystemExit(f"companies disagree about their periods: {sorted(spans)}")
    periods, period_from, period_to = spans.pop()

    def total(field: str) -> int:
        return sum(c["records"][field] for c in companies)

    targets = {"row": 0, "period": 0}
    for c in companies:
        for defect in c["_defects"]:
            key = "period" if defect["target_kind"] == "company" else "row"
            targets[key] += 1

    # The three registers as the page draws them: both companies' feeds laid
    # end to end, so a mark's index is its row in the combined population and
    # the picture has one denominator rather than two.
    #
    # GSTR-2B carries no marks, and that is a finding rather than an omission.
    # Every planted defect targets a purchase invoice, a bank line, or a
    # month — never a 2B document. The government's record is what the books
    # are being checked against, so it is the one register with nothing wrong
    # in it, and the picture should say so instead of decorating it.
    registers: dict[str, dict] = {
        "books": {
            "label": "Books, purchase register",
            "source": "tally_purchase_register.csv",
            "field": "purchase_register",
        },
        "gstr2b": {
            "label": "GSTR-2B, documents filed",
            "source": "gstr2b_<period>.json",
            "field": "gstr2b_documents",
        },
        "bank": {
            "label": "Bank, statement lines",
            "source": "bank_statement.csv",
            "field": "bank_statement",
        },
    }
    for name, register in registers.items():
        offset = 0
        marks: list[int] = []
        for c in companies:
            marks.extend(offset + row for row in c["defect_rows"].get(name, []))
            offset += c["records"][register["field"]]
        register["count"] = offset
        register["marks"] = sorted(marks)

    # One planted defect, carried through to the page in full, so the trace
    # strip quotes a line of a real file rather than a plausible-looking one.
    # R1 is chosen because it is the rule behind the headline figure, and the
    # first of its kind is chosen because "the first" is a rule anyone can
    # re-run rather than a selection someone made.
    example = None
    first = companies[0]
    feeds = SEED / first["slug"] / "feeds"
    purchase = list(csv.DictReader((feeds / "tally_purchase_register.csv").open(encoding="utf-8")))
    for defect in first["_defects"]:
        if defect["expected_rule"] != "R1" or defect["target_kind"] != "purchase_invoice":
            continue
        rows = first["defect_rows"]["books"]
        wanted = norm_invoice_no(defect["natural_key"]["number"])
        for index in rows:
            if norm_invoice_no(purchase[index]["Voucher No"]) != wanted:
                continue
            row = purchase[index]
            example = {
                "company": first["name"],
                "file": f"seed/{first['slug']}/feeds/tally_purchase_register.csv",
                # Humans count a CSV from one and the header is line one, so
                # the row a person would find in an editor is index + 2.
                "line": index + 2,
                "rule": defect["expected_rule"],
                "defect_type": defect["defect_type"],
                "period": defect["period"],
                "amount": defect["amount"],
                "note": defect["note"],
                "columns": {
                    "Date": row["Date"],
                    "Particulars": row["Particulars"],
                    "Voucher No": row["Voucher No"],
                    "Invoice Value": row["Invoice Value"],
                },
                "normalised_number": wanted,
            }
            break
        if example:
            break
    if example is None:
        raise SystemExit("no R1 purchase-invoice defect found to use as the traced example")

    # Every planted defect, in the order the ledger produced them, with the
    # amount each one carries. The landing page needs these to state a running
    # subtotal that is true at every step rather than a number counting up
    # from zero to a destination: a figure that is only correct when the
    # animation finishes is a figure that is wrong while anyone is watching it.
    #
    # Sorted by period, then by amount, so the sequence is the ledger's order
    # and not the answer key's file order. Amounts stay strings: they are
    # rupees, and this repository does not put rupees through a float.
    defects = []
    for c in companies:
        for d in c["_defects"]:
            defects.append(
                {
                    "company": c["slug"],
                    "rule": d["expected_rule"],
                    "defect_type": d["defect_type"],
                    "period": d["period"],
                    "amount": d["amount"],
                    "target": "period" if d["target_kind"] == "company" else "row",
                    "register": {
                        "purchase_invoice": "books",
                        "bank_txn": "bank",
                    }.get(d["target_kind"]),
                }
            )
    defects.sort(key=lambda d: (d["period"], Decimal(d["amount"])))

    # The running subtotal, precomputed, so nothing downstream has to add two
    # rupee strings together in JavaScript.
    running = Decimal("0")
    for d in defects:
        running += Decimal(d["amount"])
        d["cumulative"] = f"{running:.2f}"

    # The two figures the page leads with, derived instead of typed.
    #
    # They were literals in the markup, which on this page of all pages was
    # the wrong way round: everything else states its provenance and these two
    # were the largest numbers on the screen. Both check out against the seed,
    # which is why they are computed here rather than removed.
    #
    # The exposure is rule R1 and only R1. It is not every defect: R7 alone
    # carries 18.5 crore of revenue-concentration amounts, and adding rules
    # whose amounts are different quantities to each other produces a total of
    # nothing in particular. `reporting.py` sums R1 for `itc_at_risk` and this
    # agrees with it by construction.
    #
    # The second line is the part of that exposure governed by the nearest
    # Sec 16(4) cut-off. Credit for an invoice of a financial year can be
    # claimed until 30 November of the following one, so an invoice's deadline
    # follows from its period and is not stored: April onwards belongs to the
    # year it is in, January to March to the year before.
    def sec_16_4_deadline(period: str) -> str:
        year, month = (int(part) for part in period.split("-"))
        financial_year = year if month >= 4 else year - 1
        return f"{financial_year + 1}-11-30"

    exposure = [d for d in defects if d["rule"] == "R1"]
    by_deadline: dict[str, list[dict]] = defaultdict(list)
    for d in exposure:
        by_deadline[sec_16_4_deadline(d["period"])].append(d)
    soonest = min(by_deadline)

    def rupees(rows: list[dict]) -> str:
        return f"{sum(Decimal(r['amount']) for r in rows):.2f}"

    headline = {
        "rule": "R1",
        "label": "Input tax credit paid and not claimable",
        "amount": rupees(exposure),
        "defects": len(exposure),
        "before_next_deadline": {
            "deadline": soonest,
            "amount": rupees(by_deadline[soonest]),
            "defects": len(by_deadline[soonest]),
        },
    }

    payload = {
        "_comment": (
            "Generated by scripts/build_landing_aggregates.py from seed/. "
            "Every value is a count of seeded records or a field of the "
            "evaluation answer key. Do not edit by hand."
        ),
        "generated_on": date.today().isoformat(),
        "companies": companies,
        "periods": periods,
        "period_from": period_from,
        "period_to": period_to,
        "headline": headline,
        "registers": registers,
        "defects": defects,
        "example": example,
        # How the planted defects divide by what they point AT, which is the
        # only split the picture can honour. It is deliberately not the
        # row-level/period-level split the evaluation reports: those describe
        # how a rule is *scored*, and the two classifications cross. A
        # `bank_timing_gap` is scored at period level and still targets one
        # statement line, so adding the two evaluation figures together would
        # count those defects twice. Counting targets cannot.
        "targets": targets,
        # Cells the picture actually draws, which is larger than the number of
        # row-targeted defects and must not be quoted as a defect count. The
        # eleven `duplicate_invoice` defects each occupy two rows of the
        # register, because being booked twice is what makes them defects.
        "cells_drawn": sum(len(r["marks"]) for r in registers.values()),
        "totals": {
            "companies": len(companies),
            "purchase_register": total("purchase_register"),
            "sales_register": total("sales_register"),
            "ledger_entries": total("ledger_entries"),
            "gstr2b_documents": total("gstr2b_documents"),
            "bank_statement": total("bank_statement"),
            "planted": sum(c["evaluation"]["planted"] for c in companies),
            "detected": sum(c["evaluation"]["detected"] for c in companies),
            "missed": sum(c["evaluation"]["missed"] for c in companies),
            "false_positives": sum(c["evaluation"]["false_positives"] for c in companies),
        },
    }

    for c in companies:
        del c["_defects"]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    t = payload["totals"]
    print(
        f"  {t['companies']} companies, {periods} periods "
        f"({period_from} to {period_to})\n"
        f"  books {t['purchase_register']}, GSTR-2B {t['gstr2b_documents']}, "
        f"bank {t['bank_statement']}\n"
        f"  planted {t['planted']}, detected {t['detected']}, "
        f"missed {t['missed']}, invented {t['false_positives']}"
    )


if __name__ == "__main__":
    main()
